version: '3.8'

services:

  dreizettplus-web:
    container_name: dreizettplus-web
    image: php:8.0.28-apache
    build:
      context: ./
      dockerfile: dp.dockerfile
  
    ports:
      - 80:80
      
    volumes:
      - ..:/var/www/html/
      - ./config/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

  dreizettplus-mysql:
    container_name: dreizettplus-mysql
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    command: [
        '--default-authentication-plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_general_ci',
        '--character-set-client-handshake=false',
        '--join-buffer-size=512K',
        '--key-buffer-size=0',
        '--innodb-buffer-pool-size=512M',
        '--innodb-log-file-size=64M'
    ]
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'mysql'
    volumes:
      - dreizettplus-mysql:/var/lib/mysql

volumes:
  dreizettplus-web:
  dreizettplus-mysql:
